[server]
port = 5000
address = "0.0.0.0"
headless = true
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#05070a"
secondaryBackgroundColor = "#0d1117"
textColor = "#e6edf3"
primaryColor = "#00ffcc"
font = "monospace"
